### ISSUE TITLE
add grunt/gulp automation

### ISSUE THREAD

**Issue by devonkoch** [invincible-elevator/sumo-chicken#33]

**Comment by devonkoch** [comment]
optional: move bower.json into root folder for best practices sake. we can always access it in its current location (/client) via grunt/gulp and not worry about it.

**Comment by knockoutdonkey** [comment]
Did you know you can put a .bowerrc files in the root so that the libraries get downloaded to client/lib?

**Comment by devonkoch** [comment]
I did not, sounds like a good strategy.

**Comment by knockoutdonkey** [comment]
I actually just took care of it. I'll push up my commit to the repo soon.

You guys should head to https://sumo-chicken.herokuapp.com/ https://sumo-chicken.herokuapp.com/ and check out the deployment!
