### ISSUE TITLE
dashButton doesn't work in Safari

### ISSUE THREAD

**Issue by devonkoch** [invincible-elevator/sumo-chicken#51]

**Comment by shelleywang** [comment]
The error that's being thrown in Safari is: 'TypeError: undefined is not a function (evaluating 'Math.sign(player.scale.x)')'

This error isn't in Chrome/Firefox.

It looks like the Math.sign() method isn't supported in Safari: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/sign#Browser_compatibility
