### ISSUE TITLE
Differentiate the main player's chicken

### ISSUE THREAD

**Issue by shelleywang** [invincible-elevator/sumo-chicken#67]
Currently all the chickens look the same in the game, so we should have some way for users to tell which chicken is theirs.

**Comment by knockoutdonkey** [comment]
What were you guys thinking? How about putting a nickname above everyone's head? We could also just change the color of everyone else's chicken or put an arrow above the head of the main player's

**Comment by devonkoch** [comment]
+1 for the second idea.

**Comment by shelleywang** [comment]
Will be fixed by #70
