### ISSUE TITLE
Solve the mystery of the ghost chicken

### ISSUE THREAD

**Issue by knockoutdonkey** [invincible-elevator/sumo-chicken#87]

**Comment by shelleywang** [comment]
I can't explain why but whenever you start typing 'localhost:8080' into the browser URL bar and it autocompletes, this creates a socket connection to our server and introduces the 'ghost' chicken to the game. 

To test this, just restart your server and then begin typing localhost into the url bar in Chrome. You'll notice the connection console.log from node appear.

My hypothesis: the browser autocomplete actually tries to load the page in advance, and when it loads our game.js, that creates the 'ghost' socket connection.

To fix this, we can move  the 'socket = io.connect();' line from game.js into the create function in create.js.
